const stock = [
    {
        id: 1,
        nombre: 'Bocaditos para perro',
        precio: 1200,
        cantidad: 1,
        tipoMascota: 'Perro',
        imagen:'./images/productos/bocaditosPerro.jpg',
    },
    {
        id: 2,
        nombre: 'Hueso',
        precio: 800,
        cantidad: 1,
        tipoMascota: 'Perro',
        imagen:'./images/productos/huesoPerro.jpg',
    },
    {
        id: 3,
        nombre: 'Juguete Iron Man',
        precio: 2000,
        cantidad: 1,
        tipoMascota: 'Perro/Gato',
        imagen:'./images/productos/ironmanPerro.jpg',
    },
    {
        id: 4,
        nombre: 'Nuggets para perro',
        precio: 700,
        cantidad: 1,
        tipoMascota: 'Perro',
        imagen:'./images/productos/nuggetsPerro.jpg',
    },
    {
        id: 5,
        nombre: 'Juguete pescado',
        precio: 1500,
        cantidad: 1,
        tipoMascota: 'Gato',
        imagen:'./images/productos/pescadoGato.jpg',
    },
    {
        id: 6,
        nombre: 'Rascador',
        precio: 2500,
        cantidad: 1,
        tipoMascota: 'Gato',
        imagen:'./images/productos/rascadorGato.jpg',
    },
    {
        id: 7,
        nombre: 'Juguete ratita',
        precio: 1300,
        cantidad: 1,
        tipoMascota: 'Gato',
        imagen:'./images/productos/ratitaGato.jpg',
    },
    {
        id: 8,
        nombre: 'Juguete varita',
        precio: 600,
        cantidad: 1,
        tipoMascota: 'Gato',
        imagen:'./images/productos/varitaGato.jpg',
    },
]